# Generated by Django 4.2.6 on 2023-10-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='請輸入類別的英文名前三個字母。', max_length=10, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(help_text='請輸入產品詳細敘述，限定1000個字。', max_length=1000, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_inst',
            field=models.CharField(help_text='請輸入產品簡介，限定30個字。', max_length=30, verbose_name='簡介'),
        ),
    ]
