# Generated by Django 4.2.6 on 2023-10-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_name_alter_productvariant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='請輸入類別的英文名前三個字母，將會自動生成產品編號。', max_length=10, unique=True, verbose_name='編號'),
        ),
    ]
