# Generated by Django 4.2.5 on 2023-10-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_of_create']},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('o', '上架'), ('u', '下架')], default='o', help_text='上架', max_length=1, verbose_name='產品狀態'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='可自訂，也可根據類別自動生成編碼', max_length=10, verbose_name='編號'),
        ),
    ]
