# Generated by Django 4.2.6 on 2023-10-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_options_product_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_of_create']},
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('o', '上架'), ('u', '下架')], default='o', help_text='架上狀態', max_length=1, verbose_name='產品狀態'),
        ),
    ]
