# Generated by Django 4.2.6 on 2023-10-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='可自訂，也可根據類別自動生成編碼', max_length=10, null=True, verbose_name='編號'),
        ),
    ]
