# Generated by Django 4.2.6 on 2023-10-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='商品中文名'),
        ),
    ]
