# Generated by Django 4.2.6 on 2023-10-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=10, verbose_name='商品種類英文簡稱'),
        ),
    ]
