# Generated by Django 4.2.6 on 2023-11-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_productvariant_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('o', '上架'), ('u', '下架')], default='o', help_text='架上狀態', max_length=1, verbose_name='上架狀態'),
        ),
    ]
