# Generated by Django 4.2.6 on 2023-10-20 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=20, verbose_name='筆名')),
                ('author_content', models.CharField(max_length=500, verbose_name='作者簡介')),
                ('profile_image', models.ImageField(upload_to='author_image/', verbose_name='作者頭像')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('author_create_date', models.DateField(auto_now_add=True)),
                ('author_update_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='種類名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('summary', models.CharField(max_length=300, verbose_name='簡介')),
                ('post_content', models.TextField(verbose_name='內容')),
                ('image', models.ImageField(upload_to='post_image/', verbose_name='文章照片')),
                ('post_create_date', models.DateField(auto_now_add=True, verbose_name='文章創建日期')),
                ('post_update_date', models.DateField(auto_now=True, verbose_name='修改日期')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('tags', models.ManyToManyField(to='blog.tag', verbose_name='文章標籤')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(max_length=500, verbose_name='評論')),
                ('comment_create_date', models.DateField(auto_now_add=True)),
                ('comment_update_date', models.DateField()),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='評論者名稱')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='文章')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(to='blog.post', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
