# Generated by Django 4.2.6 on 2023-10-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopingCart',
        ),
    ]
