"""
Django settings for keithcoffee project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k5=v-pw0yl2w$zoe_q1duhv)6+d#kzgg3@)kq3f(9*%0(s@!_7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Django-debug-toolbar 配置
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,  # 只在 DEBUG 模式下啟用
    # 其他配置選項
}

ALLOWED_HOSTS = []


# 設定登入跟登出後跳轉到主頁
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

# 設定登入默認URL
LOGIN_URL = 'login'


SESSION_COOKIE_AGE = 86400

# 購物車的session
CART_SESSION_ID = 'cart'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar', # 因為想查看session debug狀態所以安裝的
    'product',
    'cart',
    'Home',
]

# debug 互動式工具配置
INTERNAL_IPS = [
    '127.0.0.1',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware', # 安裝debug-toolbar設置
]

ROOT_URLCONF = 'keithcoffee.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'cart.context_processors.cart', # 使Cart裡面的方法在全局都可以使用
            ],
        },
    },
]

WSGI_APPLICATION = 'keithcoffee.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'keithcoffee',
        'USER': 'root',
        'HOST': 'localhost',
        'PASSWORD': '1234567890',
        'POST': 3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

DEBUG = True


# 設置login完之後導向主頁
LOGIN_REDIRECT_URL = '/'
# 設置測試發送信箱連結會到Prompt
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# 設定信箱傳送到cmd
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 圖片路徑
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# GOOGLE API KEY 設定
GOOGLE_API_KEY = 'AIzaSyDuGRRdxyt8MTpuVIvramFP-Wt_b-jnwbQ'
BASE_COUNTRY = 'TAIWAN'


