# Generated by Django 4.2.6 on 2023-10-27 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0018_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=200, verbose_name='地址')),
                ('another_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='其他地址')),
                ('total_amount', models.IntegerField(verbose_name='總金額')),
                ('order_create', models.DateTimeField(auto_now_add=True, verbose_name='創建日期')),
                ('order_update', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('status', models.CharField(blank=True, choices=[('S', 'Shipped'), ('B', 'Backlog_order')], default='B', max_length=1, verbose_name='訂單狀態')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('price', models.IntegerField(verbose_name='總金額')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant', verbose_name='產品')),
            ],
        ),
    ]
