# Generated by Django 4.2.6 on 2023-10-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_first_name_order_last_name_order_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_create']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
    ]
